k9s:
  liveViewAutoRefresh: false
  screenDumpDir: /home/picardno/.local/state/k9s/screen-dumps
  refreshRate: 2
  maxConnRetry: 3
  readOnly: false
  noExitOnCtrlC: true
  ui:
    enableMouse: false
    headless: true
    logoless: true
    crumbsless: false
    reactive: false
    noIcons: false
    skin: transparent
  skipLatestRevCheck: false
  disablePodCounting: false
  shellPod:
    image: busybox:1.37.0
    namespace: default
    limits:
      cpu: 100m
      memory: 100Mi
  imageScans:
    enable: false
    exclusions:
      namespaces: []
      labels: {}
  logger:
    tail: 500
    buffer: 500000
    sinceSeconds: -1
    textWrap: true
    showTime: true
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
